import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart, Bar, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

const categories = ['הכול','סקרים','מפלגות','אישים ופוליטיקאים','כלכלה','ביטחון','דת ומדינה','מפלגות ערביות','מפלגות חרדיות','משפט וממשל','קמפיינים','תרחישי קואליציה','בדיקת עובדות'];
const partyProfiles = [
  {name:'הליכוד', leader:'בנימין נתניהו', color:'#2457d6'}, {name:'יש עתיד',leader:'יאיר לפיד',color:'#0ea5a4'},
  {name:'המחנה הממלכתי',leader:'בני גנץ',color:'#8293a8'}, {name:'הדמוקרטים',leader:'יאיר גולן',color:'#e25570'},
  {name:'ש״ס',leader:'אריה דרעי',color:'#6648b8'}, {name:'יהדות התורה',leader:'יצחק גולדקנופף',color:'#252a34'},
  {name:'ישראל ביתנו',leader:'אביגדור ליברמן',color:'#4b77be'}, {name:'רע״ם',leader:'מנסור עבאס',color:'#2d8d62'}
];
const fmt = value => value ? new Intl.DateTimeFormat('he-IL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : 'טרם בוצע עדכון';

function Header({page,setPage}) {
  return <><header><button className="brand" onClick={()=>setPage('home')} aria-label="דף הבית"><span>IL</span><b>Elections</b></button><nav aria-label="ניווט ראשי">
    {[['home','חדשות'],['polls','סקרים'],['parties','מפלגות ואישים'],['method','מתודולוגיה']].map(([id,label])=><button className={page===id?'active':''} key={id} onClick={()=>setPage(id)}>{label}</button>)}
  </nav><div className="status"><i/> עדכון אוטומטי</div></header><div className="disclaimer">אתר מידע עצמאי וניטרלי · אינו קשור למפלגה, מועמד/ת או ארגון חדשות כלשהו</div></>;
}
function StoryCard({story,compact=false}) { return <article className={`story ${compact?'compact':''}`}>
  <div className="story-meta"><span className="source">{story.source}</span><span>{story.category}</span><time>{fmt(story.publishedAt)}</time></div>
  <h3><a href={story.url} target="_blank" rel="noreferrer">{story.title}</a></h3>
  {!compact&&story.excerpt&&<div className="excerpt"><small>{story.excerptLabel}</small><p>{story.excerpt}</p></div>}<footer>{story.author&&<span>מאת: {story.author}</span>}<a href={story.url} target="_blank" rel="noreferrer">לכתבה המקורית באתר {story.source} ↗</a></footer>
  </article> }
function Home({data}) {
  const [query,setQuery]=useState(''); const [cat,setCat]=useState('הכול'); const [source,setSource]=useState('הכול');
  const stories=useMemo(()=>data.stories.filter(s=>(cat==='הכול'||s.category===cat)&&(source==='הכול'||s.source===source)&&JSON.stringify(s).toLowerCase().includes(query.toLowerCase())),[data,query,cat,source]);
  const cluster=data.stories.filter(s=>s.cluster==='preparations');
  return <main><section className="hero"><div><span className="eyebrow">בחירות בישראל · מרכז מידע</span><h1>כל מה שצריך לדעת,<br/><em>בלי הרעש.</em></h1><p>חדשות, נתוני סקרים והשוואת סיקור — ממקורות מגוונים, עם קטעי מקור קצרים ומסומנים.</p></div><div className="hero-stat"><b>{data.stories.length}</b><span>כתבות במאגר</span><small>עודכן {fmt(data.updatedAt)}</small></div></section>
    {cluster.length>1&&<section className="compare"><div className="section-title"><div><span className="eyebrow">השוואת סיקור</span><h2>אותו אירוע, נקודות מבט שונות</h2></div><span>{cluster.length} מקורות</span></div><p className="compare-note">הפריטים עוסקים באותו אירוע. ניתן להשוות את הנושאים והדגשים שבחר כל מקור, בלי לקבוע איזה מסגור נכון.</p><div className="comparison-grid">{cluster.map(x=><StoryCard key={x.id} story={x} compact/>)}</div></section>}
    <section><div className="section-title"><div><span className="eyebrow">העדכונים האחרונים</span><h2>חדשות הבחירות</h2></div></div><div className="filters"><label className="search"><span>⌕</span><input aria-label="חיפוש" placeholder="חיפוש מפלגה, אישיות או נושא..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="סינון מקור" value={source} onChange={e=>setSource(e.target.value)}><option>הכול</option>{[...new Set(data.stories.map(s=>s.source))].map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="chips">{categories.map(x=><button className={cat===x?'selected':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="news-grid">{stories.map(x=><StoryCard key={x.id} story={x}/>)}</div>{!stories.length&&<div className="empty"><b>{data.stories.length?'לא נמצאו תוצאות':'עדיין אין כתבות להצגה'}</b><p>{data.stories.length?'נסו חיפוש או מסנן אחר.':'האתר אינו מציג תוכן לדוגמה בשם גופי חדשות אמיתיים. כתבות מאומתות יופיעו לאחר השלמת עדכון ה־RSS הראשון.'}</p></div>}</section></main>;
}
function Polls({data}) { const colors=['#2457d6','#0ea5a4','#8293a8','#e25570','#6648b8']; if(!data.polls.length)return <main><section className="page-head"><span className="eyebrow">תמונת מצב</span><h1>לוח הסקרים</h1><p>סקרים יופיעו רק לאחר הזנה ממקור מזוהה, עם מכון, מפרסם ותאריכי עבודת שדה.</p></section><div className="notice"><b>אין עדיין סקרים מאומתים במאגר.</b> איננו מציגים נתוני הדגמה המיוחסים לגופי חדשות. ממוצע עתידי יוצג בנפרד ולעולם לא כתחזית.</div></main>; const latest=data.polls[0]; const bars=data.parties.map((party,i)=>({party,seats:latest.seats[i]})); const trends=data.polls.slice().reverse().map(p=>({date:p.published,...Object.fromEntries(data.parties.slice(0,5).map((x,i)=>[x,p.seats[i]]))})); return <main><section className="page-head"><span className="eyebrow">תמונת מצב</span><h1>לוח הסקרים</h1><p>אוסף סקרים שפורסמו לציבור. מספרי המנדטים מוצגים כפי שפורסמו במקור.</p></section><div className="notice"><b>חשוב לדעת</b> כל שורה היא סקר בודד, לא תחזית. ממוצעים מחושבים יוצגו בנפרד.</div><section className="panel"><div className="section-title"><div><h2>הסקר האחרון</h2><p>{latest.publisher} · {latest.pollster} · עבודת שדה {latest.fieldwork}</p></div><span>מדגם {latest.sample} · טעות {latest.margin}</span></div><div className="chart"><ResponsiveContainer width="100%" height={360}><BarChart data={bars} layout="vertical" margin={{right:35,left:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis dataKey="party" type="category" width={105}/><Tooltip/><Bar dataKey="seats" name="מנדטים" fill="#2457d6" radius={[5,5,5,5]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><h2>מגמות בסקרים</h2><p>שינוי במספר המנדטים בחמש המפלגות הגדולות בסקרים הבודדים.</p><div className="chart"><ResponsiveContainer width="100%" height={320}><LineChart data={trends}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis domain={['dataMin - 2','dataMax + 2']}/><Tooltip/><Legend/>{data.parties.slice(0,5).map((x,i)=><Line type="monotone" dataKey={x} stroke={colors[i]} strokeWidth={3} key={x}/>)}</LineChart></ResponsiveContainer></div></section></main> }
function Parties({stories}) {const [chosen,setChosen]=useState(null); const profiles=chosen?partyProfiles.filter(p=>p.name===chosen):partyProfiles; return <main><section className="page-head"><span className="eyebrow">מדריך פוליטי</span><h1>מפלגות ואישים</h1><p>עמודי מידע תמציתיים וריכוז הסיקור האחרון לכל מפלגה ומנהיג/ה.</p></section><div className="profiles">{profiles.map(p=><article className="profile" key={p.name}><i style={{background:p.color}}/><span>מפלגה</span><h2>{p.name}</h2><p>יו״ר: {p.leader}</p><button onClick={()=>setChosen(chosen?null:p.name)}>{chosen?'חזרה לכל המפלגות':'לסיקור האחרון'}</button>{chosen&&<div className="profile-news">{stories.filter(s=>s.parties.includes(p.name)||s.people.includes(p.leader)).map(s=><StoryCard story={s} compact key={s.id}/>)}{!stories.some(s=>s.parties.includes(p.name)||s.people.includes(p.leader))&&<p>אין כרגע כתבות תואמות במאגר.</p>}</div>}</article>)}</div></main>}
function Method() {return <main><section className="page-head"><span className="eyebrow">שקיפות</span><h1>מתודולוגיה</h1><p>איך אנחנו אוספים, מסווגים ומציגים מידע — ומה אנחנו לא עושים.</p></section><div className="method-grid">{[
 ['מקורות ועדכונים','המערכת קוראת כותרות ותיאורי RSS ממקורות ישראליים ובינלאומיים המוגדרים בקובץ sources.json. אנו נותנים קרדיט וקישור ישיר, לא עוקפים חומות תשלום ולא מעתיקים כתבות מלאות. כשל במקור אינו מוחק מידע קיים.'],
 ['קטעי מקור וסיווג','הטקסט הקצר המוצג הוא קטע מתיאור ה־RSS שסיפק המפרסם, ולא סיכום שיצר ElectionsIL. הוא מוגבל באורכו ואינו תחליף למקור. הסיווג האוטומטי נעשה לפי מילות מפתח.'],
 ['סקרים וממוצעים','סקר בודד מוצג עם מזמין/מפרסם, מכון, תאריכי עבודת השדה, מדגם וטעות דגימה כשאלה זמינים. ממוצע יחושב בשקיפות לפי משקל זמן וגודל מדגם, יוצג בנפרד ולעולם לא ייקרא תחזית.'],
 ['השוואת סיקור','כתבות על אירוע משותף מקובצות לפי ישויות, מילות מפתח וקרבת זמן. אנו מתארים הבדלים בדגש ובמסגור בלי להכתיר מקור כנכון או מוטעה.'],
 ['תיקונים','טעות עובדתית, שיוך שגוי או קישור שבור אפשר לדווח באמצעות Issues במאגר GitHub. תיקונים נשמרים בהיסטוריית Git ויתוארכו כאשר הם מהותיים.'],
 ['עצמאות וניטרליות','ElectionsIL הוא אגרגטור מידע עצמאי שאינו קשור למפלגה, מועמד/ת או גוף חדשות. אין דירוג אידאולוגי, תמיכה, התנגדות או המלצת הצבעה. סדר התוכן נקבע לפי זמן, התאמה וגיוון מקורות.']
 ].map(([h,p],i)=><section key={h}><b>0{i+1}</b><h2>{h}</h2><p>{p}</p></section>)}</div></main>}
function App(){const [page,setPage]=useState(location.hash.slice(1)||'home');const [news,setNews]=useState(null);const [polls,setPolls]=useState(null);useEffect(()=>{Promise.all([fetch(`${import.meta.env.BASE_URL}data/news.json`).then(r=>r.json()),fetch(`${import.meta.env.BASE_URL}data/polls.json`).then(r=>r.json())]).then(([n,p])=>{setNews(n);setPolls(p)})},[]);const nav=p=>{setPage(p);location.hash=p;scrollTo(0,0)};if(!news||!polls)return <div className="loading">טוענים מידע…</div>;return <><Header page={page} setPage={nav}/>{page==='home'?<Home data={news}/>:page==='polls'?<Polls data={polls}/>:page==='parties'?<Parties stories={news.stories}/>:<Method/>}<footer className="site-footer"><b>ElectionsIL</b><span>מידע לבוחרים. עצמאות, שקיפות וניטרליות.</span><small>© 2026 · קוד פתוח · אין לראות במידע המלצת הצבעה</small></footer></>};

createRoot(document.getElementById('root')).render(<App/>);
